language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  matrix:
    - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''
    - DB=pgsql db_class='Cake\Database\Driver\Postgres' db_dsn='pgsql:host=127.0.0.1;dbname=cakephp_test' db_database="cakephp_test" db_username='postgres' db_password=''
    - DB=sqlite db_class='Cake\Database\Driver\Sqlite' db_dsn='sqlite::memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  allow_failures:
    - env: DB=sqlite
    - env: DB=pqsql

before_script:
  - composer self-update
  - composer install --dev

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"

notifications:
  email: false
